Repository Part3-Team15/taskify, pull requests merged in 2024-07, with the labels that each got.

#138 🗑 Remove(#136): 안쓰는 파일 삭제 (dashboard, context)
  src/contexts/DeviceContext.tsx
  src/services/getDashboards.ts
  src/store/reducers/dashboardsSlice.ts
  src/store/store.ts
Labels: ♻️ refactor

#141 ♻️ Refactor(#121): 기본 모달 리팩토링
  src/components/Modal/ColumnDeleteModal.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/DefaultModal.tsx
  src/components/Modal/DeleteDashboardModal.tsx
  src/components/Modal/EmailExistModal.tsx
  src/components/Modal/NewColumnModal.tsx
  src/components/Modal/NotificationModal.tsx
  src/components/Modal/SignupSuccessModal.tsx
  src/components/Modal/TextModal.tsx
  src/components/Modal/index.tsx
  src/containers/dashboard/ColumnsSection.tsx
  src/containers/dashboard/edit/InvitedMemberItem.tsx
  src/containers/dashboard/edit/MemberItem.tsx
  src/containers/signin&signup/SignInForm.tsx
  src/containers/signin&signup/SignUpForm.tsx
  src/hooks/useModal.ts
  src/store/reducers/modalSlice.ts
  src/styles/globals.css
  src/types/Modal.interface.ts
  tailwind.config.ts
Labels: 🔐 auth, 🪧 modal

#143 ✨ Feat(#25): 대시보드 정보 수정 컴포넌트 추가
  src/components/Modal/NewDashboardModal.tsx
  src/containers/dashboard/edit/DashboardEdit.tsx
  src/containers/dashboard/edit/DashboardModifySection.tsx
  src/services/putService.ts
  src/types/Dashboard.interface.ts
Labels: ✨ feat, 📝 dashboard edit

#133 🎨 design(#129): 화면 세로 크기를 줄이면 레이아웃이 고장나는 버그 수정
  src/components/Sidebar/DashboardItem.tsx
  src/components/Sidebar/index.tsx
  src/containers/mydashboard/DashboardList/index.tsx
  src/containers/mydashboard/InvitedDashboardList/index.tsx
  src/containers/mydashboard/index.tsx
  tailwind.config.ts
Labels: 🐛 report, 🎨 design

#147 ♻️ refactor(#121, #114, #21): 컬럼 수정 모달 리팩토링 및 적용
  src/components/Modal/ColumnModifyModal.tsx
  src/components/Modal/ModifyColumnModal.tsx
  src/components/Modal/NewColumnModal.tsx
  src/components/Modal/index.tsx
  src/containers/dashboard/Column.tsx
  src/containers/dashboard/ColumnsSection.tsx
  src/types/Modal.interface.ts
Labels: ♻️ refactor, 🪧 modal

#148 ♻️ Refactor(#121, #22): 초대하기 모달 리팩토링 및 적용
  src/components/Header/DashboardHeader/Buttons.tsx
  src/components/Modal/InviteMemberModal.tsx
  src/components/Modal/index.tsx
  src/constants/index.ts
  src/containers/dashboard/edit/InvitedMembersSection.tsx
  src/containers/dashboard/edit/index.tsx
  src/pages/dashboard/[id]/edit.tsx
  src/services/postService.ts
  src/types/Modal.interface.ts
  src/types/post/ModalForm.interface.ts
  src/types/post/ModalPost.interface.ts
Labels: 📝 dashboard edit, 🪧 modal

#150 ♻️ Refactor: 대시보드 생성 모달 리팩토링 및 적용
  src/components/Modal/NewDashboardModal.tsx
  src/containers/mydashboard/DashboardList/index.tsx
Labels: ♻️ refactor, 📑 my dashboard, 🪧 modal

#145 ✨ Feat: 카드 DnD (대시보드 페이지)
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/containers/dashboard/Card.tsx
  src/containers/dashboard/Column.tsx
  src/containers/dashboard/ColumnsSection.tsx
  src/services/putService.ts
Labels: ✨ feat, 📄 dashboard

#159 🗑 Remove(#136): 누락된 useFetchDashboard 삭제
  src/hooks/useFetchDashboards.ts
Labels: 🛠 fix

#115 ✨ feat(#10): 랜딩페이지 제작
  public/images/landing0.svg
  public/images/landing1.svg
  public/images/landing2.svg
  public/images/landing3.svg
  public/images/landing4.svg
  public/images/landing5.svg
  src/components/Footer/index.tsx
  src/components/Header/LandingHeader.tsx
  src/pages/index.tsx
  tailwind.config.ts
Labels: ✨ feat, 🏠 landing

#161 🛠 Fix(#128): 배포 오류 해결
  src/services/deleteService.ts
Labels: 🛠 fix

#160 🛠 fix(#158): 내 대시보드 스켈레톤 key 문제 해결
  src/containers/mydashboard/InvitedDashboardList/Skeleton.tsx
  src/containers/mydashboard/InvitedDashboardList/index.tsx
Labels: 🛠 fix

#139 🛠 fix(#137): 드롭다운 클릭효과 범위 수정
  src/components/Header/UserMenuDropdown.tsx
  src/hooks/useUserDropdown.ts
  src/styles/globals.css
Labels: 🛠 fix

#163 ✨ feat(#157): 404 페이지 제작
  public/images/not-found.svg
  src/layouts/MainLayout.tsx
  src/pages/404.tsx
Labels: ✨ feat

#151 ♻️ Refactor(#121): 함수를 분리하여 타입 점검함으로써 타입 단언 방어
  src/components/Footer/index.tsx
  src/components/Header/DashboardHeader/Buttons.tsx
  src/components/Modal/InviteMemberModal.tsx
  src/components/Modal/ModifyColumnModal.tsx
  src/components/Modal/NewColumnModal.tsx
  src/components/Modal/NewDashboardModal.tsx
  src/components/Modal/index.tsx
  src/components/Sidebar/index.tsx
  src/containers/dashboard/Column.tsx
  src/containers/dashboard/ColumnsSection.tsx
  src/containers/dashboard/edit/DashboardModifySection.tsx
  src/containers/dashboard/edit/InvitedMembersSection.tsx
  src/containers/mydashboard/DashboardList/index.tsx
  src/containers/signin&signup/SignInForm.tsx
  src/containers/signin&signup/SignUpForm.tsx
  src/hooks/useModal.ts
  src/pages/index.tsx
  src/services/postService.ts
  src/store/reducers/modalSlice.ts
  src/types/Modal.interface.ts
Labels: ♻️ refactor, 🪧 modal

#164 ✨ Feat(#90): 비밀번호 암호화
  .gitignore
  package.json
  pnpm-lock.yaml
  src/containers/mypage/PwdChangeForm.tsx
  src/containers/signin&signup/SignInForm.tsx
  src/containers/signin&signup/SignUpForm.tsx
  src/utils/hashPassword.ts
Labels: 🔐 auth

#172 🛠 Fix(#77): 재요청 횟수 제한
  src/hooks/useFetchData.ts
Labels: 🛠 fix

#169 🛠 fix(#85): 헤더 수정
  src/components/Header/DashboardHeader/Buttons.tsx
  src/components/Header/DashboardHeader/MemberProfiles.tsx
  src/components/Header/DashboardHeader/index.tsx
  src/components/Header/DefaultHeader.tsx
  src/components/Header/UserMenuDropdown.tsx
Labels: 🛠 fix

#174 ✨ Feat(#173): 모달 적용하기
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/NotificationModal.tsx
  src/containers/dashboard/edit/MembersSection.tsx
  src/containers/dashboard/edit/index.tsx
  src/containers/mypage/EditProfileForm.tsx
  src/containers/mypage/PwdChangeForm.tsx
  src/hooks/useUpdateProfile.ts
  src/services/deleteService.ts
  src/types/delete/DeleteDashboardInput.interface.ts
Labels: 🪧 modal

#154 ✨ Feat(#82) : 로그인 상태에 따른 리다이렉션 구현
  src/components/Redirect/index.tsx
  src/hooks/useRedirectIfAuthenticated.ts
  src/hooks/useRedirectIfNotAuth.ts
  src/pages/_app.tsx
Labels: ✨ feat, 🔐 auth

#186 ❗️HOTFIX(#82): 리다이렉션 중 이전 모달 사용하는 부분 수정
  src/hooks/useRedirectIfAuthenticated.ts
  src/hooks/useRedirectIfNotAuth.ts
Labels: 🛠 fix

#187 🛠 fix(#185): 대시보드 이름 수정 시 15자 길이 제한
  src/containers/dashboard/edit/DashboardModifySection.tsx
  src/containers/signin&signup/SignUpForm.tsx
Labels: 🛠 fix, 📝 dashboard edit

#178 ✨ Feat: 대시보드 초대 알림 기능 추가
  package.json
  pnpm-lock.yaml
  src/components/Header/DefaultHeader/index.tsx
  src/components/Header/LandingHeader/index.tsx
  src/components/InviteNotice/index.tsx
  src/constants/index.ts
  src/hooks/useFetchData.ts
  src/pages/_app.tsx
Labels: ✨ feat

#184 ✨ Feat(#11): 할 일 카드 생성 모달 컴포넌트 구현
  next.config.mjs
  public/icons/carrot-down.svg
  src/components/Modal/EditCardModal/MemberProfile.tsx
  src/components/Modal/EditCardModal/MembersDropDown.tsx
  src/components/Modal/EditCardModal/TagsWrapper.tsx
  src/components/Modal/EditCardModal/index.tsx
  src/components/Modal/NewDashboardModal.tsx
  src/components/Modal/index.tsx
  src/containers/dashboard/Column.tsx
  src/hooks/useModal.ts
  src/services/postService.ts
  src/types/Modal.interface.ts
  src/utils/formatDateTime.ts
Labels: ✨ feat, 🪧 modal

#190 🎨 Design(#171) 헤더 관련 디자인 수정사항
  src/components/Header/DashboardHeader/Buttons.tsx
  src/components/Header/DashboardHeader/MemberProfiles.tsx
  src/components/Header/DashboardHeader/index.tsx
Labels: 🎨 design, 🛠 fix

#193 🛠 fix(#168): 대시보드 초대 알림 문제 해결
  src/components/InviteNotice/index.tsx
Labels: 🛠 fix

#195 🛠 fix(#11): 카드 생성 모달 태그 색상 추가
  src/components/Modal/EditCardModal/TagsWrapper.tsx
  src/components/Modal/EditCardModal/index.tsx
  src/components/Tags/index.tsx
Labels: 🛠 fix

#191 🎨 design(#171): 로그인/회원가입 여백설정
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: 🎨 design

#196 🛠 fix(#168): 초대알림에서 user 접근 시 에러 해결
  src/components/InviteNotice/index.tsx
  src/layouts/MainLayout.tsx
  src/pages/_app.tsx
Labels: 🛠 fix

#180 ✨ Feat: 할일 카드 모달
  public/icons/kebab.svg
  src/components/Modal/TodoCardModal/Comment.tsx
  src/components/Modal/TodoCardModal/EditDropdown.tsx
  src/components/Modal/TodoCardModal/TodoCardModal.tsx
  src/components/Modal/index.tsx
  src/components/Tags/index.tsx
  src/containers/dashboard/Card.tsx
  src/containers/dashboard/Column.tsx
  src/hooks/useModal.ts
  src/services/deleteService.ts
  src/services/getService.ts
  src/services/postService.ts
  src/services/putService.ts
  src/types/Modal.interface.ts
  src/types/post/CommentForm.interface.ts
  src/utils/formatDate.ts
Labels: ✨ feat, 📄 dashboard

#181 ✨ Feat(#155): 대시보드 공유 기능
  src/components/Header/DashboardHeader/MemberProfiles.tsx
  src/components/Header/DashboardHeader/index.tsx
  src/components/Header/UserMenuDropdown.tsx
  src/components/Header/UserProfile.tsx
  src/components/Header/index.tsx
  src/components/Modal/NewDashboardModal.tsx
  src/components/Toggle/index.tsx
  src/containers/dashboard/edit/DashboardModifySection.tsx
  src/containers/dashboard/edit/MemberList.tsx
  src/containers/dashboard/edit/MembersSection.tsx
  src/containers/dashboard/edit/index.tsx
  src/layouts/MainLayout.tsx
  src/pages/404.tsx
  src/services/axios.ts
  src/services/postService.ts
  src/utils/shareAccount.ts
Labels: ✨ feat, 📄 dashboard

#204 🛠 fix(#162): 프리뷰 안뜨는 문제 수정
  public/preview.png
  src/pages/_app.tsx
Labels: 🎨 design, 🛠 fix

#203 ❗️ HOTFIX(#24): 대시보드 생성자 멤버 삭제 불가능하게 변경
  src/containers/dashboard/edit/MemberItem.tsx
  src/styles/globals.css
Labels: 🛠 fix, 📝 dashboard edit

#192 🎨 design(#171): 랜딩 페이지 디자인 수정
  package.json
  pnpm-lock.yaml
  public/images/landing1.png
  public/images/landing2.png
  public/images/landing3.png
  src/components/Footer/index.tsx
  src/components/Header/index.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: 🎨 design, 🏠 landing

#201 🛠 fix(#200): 같은 대시보드 초대를 하나만 받을 수 있도록 수정
  src/containers/mydashboard/InvitedDashboardList/ItemList.tsx
  src/containers/mydashboard/InvitedDashboardList/index.tsx
Labels: 🛠 fix, 📑 my dashboard

#197 🎨 Design(#153): 다크 모드 설정
  package.json
  pnpm-lock.yaml
  public/icons/kebab-white.svg
  public/icons/logo-white.svg
  public/icons/plus-white.svg
  public/icons/search-w.svg
  public/icons/theme-dark.svg
  public/icons/theme-light.svg
  public/icons/theme.svg
  public/icons/x-white.svg
  public/images/logo_sign-white.svg
  src/components/Button/CancelButton.tsx
  src/components/Button/ThemeChangeButton.tsx
  src/components/Header/DashboardHeader/index.tsx
  src/components/Header/DefaultHeader/index.tsx
  src/components/Header/UserMenuDropdown.tsx
  src/components/Input/ImageInput.tsx
  src/components/Input/PwdInput.tsx
  src/components/Modal/EditCardModal/index.tsx
  src/components/Modal/TodoCardModal/Comment.tsx
  src/components/Modal/TodoCardModal/EditDropdown.tsx
  src/components/Modal/TodoCardModal/TodoCardModal.tsx
  src/components/Pagination/index.tsx
  src/components/ProfileIcon/index.tsx
  src/components/Sidebar/DashboardItem.tsx
  src/components/Sidebar/index.tsx
  src/containers/dashboard/Card.tsx
  src/containers/dashboard/Column.tsx
  src/containers/dashboard/ColumnsSection.tsx
  src/containers/dashboard/edit/DashboardModifySection.tsx
  src/containers/dashboard/edit/InvitedMemberList.tsx
  src/containers/dashboard/edit/InvitedMembersSection.tsx
  src/containers/dashboard/edit/MemberList.tsx
  src/containers/dashboard/edit/MembersSection.tsx
  src/containers/dashboard/edit/index.tsx
  src/containers/mydashboard/DashboardList/index.tsx
  src/containers/mydashboard/InvitedDashboardList/ItemList.tsx
  src/containers/mydashboard/InvitedDashboardList/SearchBar.tsx
  src/containers/mydashboard/InvitedDashboardList/Skeleton.tsx
  src/containers/mydashboard/InvitedDashboardList/index.tsx
  src/containers/mypage/EditProfileForm.tsx
  src/containers/signin&signup/PwdInputWithLabel.tsx
  src/containers/signin&signup/SignUpForm.tsx
  src/containers/signin&signup/TextInputWithLabel.tsx
  src/containers/signin&signup/TopLogoSection.tsx
  src/layouts/MainLayout.tsx
  src/pages/_app.tsx
  src/pages/mypage/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 🎨 design

#205 ✨ Feat(#18): 할 일 카드 수정 모달 구현
  src/components/Modal/EditCardModal/ColumnsDropDown.tsx
  src/components/Modal/EditCardModal/index.tsx
  src/components/Modal/TodoCardModal/EditDropdown.tsx
  src/containers/dashboard/Column.tsx
  src/hooks/useModal.ts
  src/services/putService.ts
  src/types/Modal.interface.ts
  src/utils/formatDateTime.ts
Labels: ✨ feat, 🪧 modal

#202 🛠 fix(#198): 초대목록 변동 생길 경우를 고려해 필터링 기준을 시간으로 변경
  src/components/InviteNotice/index.tsx
  src/containers/mydashboard/InvitedDashboardList/index.tsx
Labels: 🛠 fix, 📑 my dashboard

#212 ✨ Feat(#210): 할 일 카드 수정 및 생성 추가 기능 구현
  public/icons/spinner.svg
  src/components/Modal/EditCardModal/index.tsx
  src/components/Modal/TodoCardModal/EditDropdown.tsx
  src/components/Modal/TodoCardModal/TodoCardModal.tsx
  src/containers/dashboard/Column.tsx
  src/services/postService.ts
  src/services/putService.ts
  src/types/Modal.interface.ts
  src/types/post/EditModalPostData.interface.ts
Labels: ✨ feat, 🪧 modal

#216 🛠 Fix(#153): 다크모드로 바뀐 버튼 디자인 복귀
  src/containers/dashboard/edit/index.tsx
Labels: 🛠 fix

#219 ✨ Feat(#209): 폰트 적용
  src/components/ProfileIcon/index.tsx
  src/pages/_app.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 🎨 design

#218 🎨 design(#217): 다크모드 수정
  src/components/Button/CancelButton.tsx
  src/components/Modal/EditCardModal/ColumnsDropDown.tsx
  src/components/Modal/EditCardModal/MembersDropDown.tsx
  src/components/Modal/EditCardModal/index.tsx
  src/components/Modal/TodoCardModal/TodoCardModal.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 🎨 design

#214 🛠 Fix: 대시보드 페이지 내 버그 수정
  public/icons/comment-empty.svg
  public/icons/comment.svg
  src/components/Modal/EditCardModal/MemberProfile.tsx
  src/components/Modal/EditCardModal/index.tsx
  src/components/Modal/TodoCardModal/Comment.tsx
  src/components/Modal/TodoCardModal/EditDropdown.tsx
  src/components/Modal/TodoCardModal/TodoCardModal.tsx
  src/components/Modal/index.tsx
  src/containers/dashboard/Card.tsx
  src/containers/dashboard/Column.tsx
  src/containers/dashboard/ColumnSkeleton.tsx
  src/containers/dashboard/ColumnsSection.tsx
  src/pages/dashboard/[id]/index.tsx
  src/utils/formatDate.ts
Labels: 🛠 fix, 📄 dashboard

#199 ♻️ refactor(#167): 내 대시보드 페이지 서버 사이드 렌더링 적용
  package.json
  pnpm-lock.yaml
  src/containers/mydashboard/DashboardList/index.tsx
  src/containers/mydashboard/InvitedDashboardList/index.tsx
  src/hooks/useFetchData.ts
  src/hooks/useSignIn.ts
  src/hooks/useUserDropdown.ts
  src/pages/mydashboard/index.tsx
  src/utils/createAuthHeaders.ts
Labels: ♻️ refactor, 📑 my dashboard

#213 ✨ feat(#188): 대시보드 즐겨찾기 추가
  src/components/Sidebar/index.tsx
  src/containers/dashboard/edit/DashboardModifySection.tsx
  src/containers/dashboard/edit/index.tsx
  src/db/dbConnect.ts
  src/hooks/useFetchData.ts
  src/models/Favorite.ts
  src/models/User.ts
  src/pages/api/favorites/[id].ts
  src/pages/api/users/[id].ts
  src/pages/api/users/index.ts
  src/pages/dashboard/[id]/edit.tsx
  src/services/deleteService.ts
  src/services/getService.ts
  src/services/postService.ts
  src/types/Dashboard.interface.ts
  src/utils/favoriteDashboard.ts
  tsconfig.json
Labels: ✨ feat

#220 🎨 design(#13): 대시보드 컬럼 길이 수정
  src/containers/dashboard/Column.tsx
  src/containers/dashboard/ColumnsSection.tsx
Labels: 🎨 design, 🛠 fix, 📄 dashboard

#222 🛠 fix(#212, #211): 배포 오류 해결
  src/components/Modal/EditCardModal/index.tsx
  src/services/postService.ts
  src/services/putService.ts
  src/types/Modal.interface.ts
Labels: 🛠 fix

#224 🛠 fix(#198): 첫 번째 초대도 알람 올 수 있게 변경
  src/components/InviteNotice/index.tsx
Labels: 🛠 fix

#221 🎨 design(#188): 사이드바 즐겨찾기 글자 수정
  src/components/Button/ThemeChangeButton.tsx
  src/components/Sidebar/index.tsx
Labels: 🎨 design

#228 🎨 design(#153): 다크모드 버튼 위치 수정
  public/icons/logo-s.svg
  public/icons/logo-small.svg
  src/components/Button/ThemeChangeButton.tsx
  src/components/Header/DashboardHeader/index.tsx
  src/components/Header/DefaultHeader/index.tsx
  src/components/Sidebar/index.tsx
  src/components/Toggle/index.tsx
  src/containers/dashboard/edit/DashboardModifySection.tsx
  src/containers/mydashboard/DashboardList/index.tsx
  src/pages/index.tsx
Labels: 🎨 design

#227 ♻️ refactor(#226): 즐겨찾기 기능 최적화
  src/components/Button/ThemeChangeButton.tsx
  src/components/Sidebar/index.tsx
  src/containers/dashboard/edit/DashboardModifySection.tsx
  src/containers/dashboard/edit/index.tsx
  src/hooks/useFavoriteUser.ts
  src/hooks/useUserDropdown.ts
  src/services/getService.ts
  src/store/reducers/favoritesUserSlice.ts
  src/store/store.ts
  src/utils/favoriteDashboard.ts
Labels: ♻️ refactor

#225 ✨ Feat: 카드목록, 댓글목록 무한스크롤 적용 & 기타 리팩토링
  src/components/Modal/TodoCardModal/Comment.tsx
  src/components/Modal/TodoCardModal/index.tsx
  src/containers/dashboard/Card.tsx
  src/containers/dashboard/Column.tsx
  src/containers/dashboard/ColumnSkeleton.tsx
  src/containers/dashboard/ColumnsSection.tsx
  src/containers/dashboard/index.tsx
  src/pages/dashboard/[id]/index.tsx
  src/services/getService.ts
  src/utils/formatDate.ts
Labels: 📄 dashboard

#215 📝 docs(#165): README.md 수정
  README.md
Labels: 📝 docs

#236 🛠 Fix(#234): 즐겨찾기 간단한 수정
  src/components/Sidebar/index.tsx
  src/containers/dashboard/edit/DashboardModifySection.tsx
Labels: 🎨 design, 🛠 fix

#239 💬 Comment(#238): 코드 가독성 향상을 위한 구조 변경 / 주석 추가
  src/components/Button/ActionButton.tsx
  src/components/Button/CancelButton.tsx
  src/components/Button/ModalActionButton.tsx
  src/components/Button/ModalCancelButton.tsx
  src/components/Button/NavButton.tsx
  src/components/Header/DashboardHeader/Buttons.tsx
  src/components/Header/DashboardHeader/MemberProfiles.tsx
  src/components/Header/DashboardHeader/index.tsx
  src/components/Header/DefaultHeader/index.tsx
  src/components/Header/LandingHeader/index.tsx
  src/components/Header/UserMenuDropdown.tsx
  src/components/Header/UserProfile.tsx
  src/components/Header/index.tsx
  src/components/Input/ImageInput.tsx
  src/components/Input/PwdInput.tsx
  src/components/InviteNotice/index.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/InviteMemberModal.tsx
  src/components/Modal/ModifyColumnModal.tsx
  src/components/Modal/NewColumnModal.tsx
  src/components/Modal/NotificationModal.tsx
  src/components/Pagination/index.tsx
  src/components/ProfileIcon/index.tsx
  src/components/Redirect/index.tsx
  src/components/Toggle/index.tsx
  src/containers/dashboard/edit/InvitedMemberItem.tsx
  src/containers/dashboard/edit/InvitedMemberList.tsx
  src/containers/dashboard/edit/InvitedMembersSection.tsx
  src/containers/dashboard/edit/MemberItem.tsx
  src/containers/dashboard/edit/MemberList.tsx
  src/containers/dashboard/edit/MembersSection.tsx
  src/containers/dashboard/edit/index.tsx
  src/containers/mypage/EditProfileForm.tsx
  src/hooks/useDeleteData.ts
  src/hooks/useFetchData.ts
  src/hooks/useModal.ts
  src/hooks/useUpdateProfile.ts
  src/hooks/useUserDropdown.ts
  src/layouts/MainLayout.tsx
  src/services/axios.ts
  src/styles/globals.css
  src/utils/generateTagIndex.ts
  src/utils/getProfileColorStyle.ts
  src/utils/hashPassword.ts
  src/utils/shareAccount.ts
Labels: 📝 docs

#240 내 내시보드, 사이드바 리팩토링
  src/components/InviteNotice/index.tsx
  src/components/Sidebar/index.tsx
  src/containers/dashboard/edit/DashboardModifySection.tsx
  src/containers/mydashboard/DashboardList/index.tsx
  src/hooks/useFetchData.ts
  src/hooks/useSignIn.ts
  src/hooks/useUserDropdown.ts
  src/pages/mydashboard/index.tsx
Labels: ♻️ refactor

#241 ♻️ Refactor(#237): queryCache를 이용한 리다이렉트 개선
  src/components/Header/DashboardHeader/MemberProfiles.tsx
  src/components/Header/DashboardHeader/index.tsx
  src/components/Redirect/index.tsx
  src/containers/dashboard/ColumnsSection.tsx
  src/containers/dashboard/edit/DashboardModifySection.tsx
  src/containers/dashboard/edit/InvitedMembersSection.tsx
  src/containers/dashboard/edit/MembersSection.tsx
  src/containers/dashboard/edit/index.tsx
  src/hooks/useDeleteData.ts
  src/hooks/useFetchData.ts
  src/hooks/useRedirect.ts
  src/hooks/useRedirectIfAuth.ts
  src/hooks/useRedirectIfNoPermission.ts
  src/hooks/useRedirectIfNotAuth.ts
  src/hooks/useRedirectIfNotMember.ts
  src/pages/_app.tsx
Labels: ♻️ refactor

#242 ♻️ Refactor: Tanstack Query 캐싱 리팩토링
  src/components/Modal/TodoCardModal/index.tsx
  src/containers/dashboard/Column.tsx
  src/hooks/useInfiniteScroll.ts
Labels: ♻️ refactor

#244 🎨 design(#10): 랜딩 페이지 모바일 사이즈 수정
  src/pages/index.tsx
Labels: 🎨 design, 🛠 fix

#235 📝 Docs(#233): README.md 완성
  README.md
Labels: 📝 docs

#246 📝 docs(#233): README 보충
  README.md
Labels: 📝 docs

#247 design(#10): 랜딩 페이지 설명 수정
  src/pages/index.tsx
Labels: 🎨 design
