Repository Part3-Team15/taskify, pull requests merged in 2024-06, with the labels that each got.

#5 ⚙️ Chore: 프로젝트 초기 설정
  .commitlintrc.ts
  .eslintrc.json
  .github/ISSUE_TEMPLATE/✨-feat-이슈-템플릿.md
  .github/pull_request_template.md
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .prettierrc
  README.md
  next.config.mjs
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  public/favicon.ico
  public/icons/search.svg
  public/images/logo_large.png
  src/components/Button/index.tsx
  src/constants/index.ts
  src/containers/dashboard/index.tsx
  src/contexts/DeviceContext.tsx
  src/hooks/useFetchData.ts
  src/layouts/MainLayout.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/services/getDashboards.ts
  src/styles/globals.css
  src/types/Dashboard.interface.ts
  src/utils/formatDateWithDot.tsformatDateWithDot.ts
  tailwind.config.ts
  tsconfig.json
Labels: ⚙️ chore

#33 ⚙️ Chore: tailwind 컬러 팔레트 및 반응형 브레이크 포인트 세팅
  .prettierignore
  src/styles/globals.css
  tailwind.config.ts
Labels: ⚙️ chore

#34 ✨ Feat: 페이지 라우팅 설정
  src/pages/dashboard/[id]/edit.tsx
  src/pages/dashboard/[id]/index.tsx
  src/pages/index.tsx
  src/pages/mydashboard/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: ✨ feat

#39 ⚙️ Chore: 배포하기
  .github/workflows/deploy.yml
  .github/workflows/deploy_dev.yml
  build.sh
  pnpm-lock.yaml
Labels: ⚙️ chore

#43 ✨ Feat: 유저 기능 구현
  src/containers/signin/SignInForm.tsx
  src/hooks/useSignIn.ts
  src/pages/_app.tsx
  src/pages/signin/index.tsx
  src/store/reducers/userSlice.ts
  src/store/store.ts
Labels: ✨ feat, 🔐 auth

#46 ⚙️ Chore: eslintrc.json 변경에 따른 패키지 추가
  package.json
  pnpm-lock.yaml
Labels: ⚙️ chore, 🛠 fix

#47 ⚙️ Chore: 유저 기능 관련 패키지 추가
  package.json
  pnpm-lock.yaml
Labels: ⚙️ chore, 🔐 auth

#50 ✨ Feat: 공용 버튼 컴포넌트 구현
  public/icons/plusbox.svg
  src/components/Button/index.tsx
  src/pages/index.tsx
  tailwind.config.ts
Labels: ✨ feat

#55 ✨ feat: useFetchData 커스텀 훅
  src/hooks/useFetchData.ts
Labels: ✨ feat, 🔐 auth

#44 ✨ Feat: generateTagIndex 함수 구현
  src/utils/generateTagIndex.ts
Labels: ✨ feat

#56 ⚙️ Chore: scope 적는 것 강제하도록 변경 (이슈넘버 적기)
  .commitlintrc.ts
Labels: ⚙️ chore

#63 ♻️ Refactor: 서비스 로직 분리 & useFetch 커스텀훅 리팩토링
  package.json
  pnpm-lock.yaml
  src/hooks/useFetchDashboards.ts
  src/hooks/useFetchData.ts
  src/services/axios.ts
  src/services/getService.ts
  src/store/reducers/dashboardsSlice.ts
  src/store/store.ts
  src/types/Dashboard.interface.ts
Labels: ♻️ refactor

#65 ✨ Feat(#2): Sidebar 제작
  public/icons/crown.svg
  public/icons/logo.svg
  public/icons/plus.svg
  src/components/Sidebar/DashboardItem.tsx
  src/components/Sidebar/index.tsx
Labels: ✨ feat, 📑 my dashboard, 📄 dashboard, 📝 dashboard edit, 🪪 mypage

#68 ✨ Feat(#6, #7): 로그인, 회원가입 페이지
  .eslintrc.json
  package.json
  public/icons/invisibility.svg
  public/icons/visibility.svg
  public/images/logo_sign.svg
  src/containers/signin&signup/PwdInputWithLabel.tsx
  src/containers/signin&signup/SignInForm.tsx
  src/containers/signin&signup/SignUpForm.tsx
  src/containers/signin&signup/TextInputWithLabel.tsx
  src/containers/signin&signup/TopLogoSection.tsx
  src/containers/signin/SignInForm.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  tailwind.config.ts
Labels: ✨ feat, 🔐 auth

#75 ⚙️ Chore(#74): tailwind.config.ts 컬러 수정 및 기존 컬러 클래스명 변경
  src/containers/signin&signup/PwdInputWithLabel.tsx
  src/containers/signin&signup/SignInForm.tsx
  src/containers/signin&signup/SignUpForm.tsx
  src/containers/signin&signup/TextInputWithLabel.tsx
  src/containers/signin&signup/TopLogoSection.tsx
  src/layouts/MainLayout.tsx
  src/pages/signin/index.tsx
  tailwind.config.ts
Labels: ⚙️ chore

#71 ✨ Feat: 컬럼 섹션 & 개별 컬럼
  public/icons/gear.svg
  public/icons/plus-filled.svg
  src/components/Sidebar/DashboardItem.tsx
  src/components/Sidebar/index.tsx
  src/containers/dashboard/Column.tsx
  src/containers/dashboard/ColumnsSection.tsx
  src/layouts/MainLayout.tsx
  src/pages/dashboard/[id]/index.tsx
  src/types/Column.interface.ts
  tailwind.config.ts
Labels: ✨ feat, 📄 dashboard

#81 ⚙️ chore(#79): pnpm-lock.yaml 최신화
  pnpm-lock.yaml
Labels: ⚙️ chore, 🛠 fix

#78 ✨ Feat(#9): Header 컴포넌트 구현
  .eslintrc.json
  public/icons/logo-white-s.svg
  public/icons/logo-white.svg
  public/icons/plus-boxed.svg
  src/components/Header/DashboardHeader.tsx
  src/components/Header/DefaultHeader.tsx
  src/components/Header/LandingHeader.tsx
  src/components/Header/UserMenuDropdown.tsx
  src/components/Header/UserProfile.tsx
  src/components/Header/index.tsx
  src/components/ProfileIcon/index.tsx
  src/layouts/MainLayout.tsx
  src/pages/signup/index.tsx
  src/services/getService.ts
  src/styles/globals.css
  src/types/Member.interface.ts
  src/utils/findDashboardById.ts
  tailwind.config.ts
Labels: ✨ feat

#80 ✨ Feat(#16): mydashboard 페이지 DashboardList 컴포넌트 구현
  public/icons/arrow-black.svg
  public/icons/arrow-white.svg
  src/components/Sidebar/index.tsx
  src/containers/mydashboard/DashboardList/index.tsx
  src/containers/mydashboard/index.tsx
  src/pages/mydashboard/index.tsx
Labels: ✨ feat, 🪪 mypage

#91 ⚙️ chore(#78): 프리티어 플러그인 설치에 따른 패키지 업데이트
  package.json
  pnpm-lock.yaml
Labels: ⚙️ chore, 🛠 fix

#89 ♻️ Refactor(#86): 버튼 디자인 클래스 생성 및 버튼 컴포넌트 개선
  src/components/Button/ActionButton.tsx
  src/components/Button/CancelButton.tsx
  src/components/Button/ModalActionButton.tsx
  src/components/Button/ModalCancelButton.tsx
  src/components/Button/index.tsx
  src/components/Header/DashboardHeader.tsx
  src/containers/dashboard/Column.tsx
  src/containers/dashboard/ColumnsSection.tsx
  src/containers/mydashboard/DashboardList/index.tsx
  src/containers/signin&signup/SignInForm.tsx
  src/containers/signin&signup/SignUpForm.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ♻️ refactor

#93 🛠 fix(#16): 대시보드 리스트 버튼 비활성화 추가
  src/containers/mydashboard/DashboardList/index.tsx
Labels: 🎨 design, 🛠 fix, 📑 my dashboard

#95 🎨 design(#31): 레이아웃 크기, 색상 수정
  src/containers/dashboard/ColumnsSection.tsx
  src/containers/mydashboard/index.tsx
  src/layouts/MainLayout.tsx
Labels: 🎨 design

#96 ⚙️ Chore: Tanstack Query 업그레이드
  package.json
  pnpm-lock.yaml
  src/hooks/useFetchDashboards.ts
  src/hooks/useFetchData.ts
  src/hooks/useSignIn.ts
  src/pages/_app.tsx
Labels: ⚙️ chore, ♻️ refactor

#100 ✨ Feat(#8): 프로필 수정 기능
  next.config.mjs
  public/icons/edit.svg
  public/icons/plus-violet.svg
  public/icons/x.svg
  src/components/Header/UserProfile.tsx
  src/components/Input/ImageInput.tsx
  src/components/ProfileIcon/index.tsx
  src/containers/mypage/EditProfileForm.tsx
  src/containers/signin&signup/SignInForm.tsx
  src/hooks/useUpdateProfile.ts
  src/pages/mypage/index.tsx
  src/services/postService.ts
  src/services/putService.ts
  src/store/reducers/userSlice.ts
  src/styles/globals.css
  src/types/post/UpdateProfileForm.interface.ts
  src/types/post/UploadImageForm.interface.ts
  tailwind.config.ts
Labels: ✨ feat, 🪪 mypage

#99 ✨ feat(#20) 내가 받은 초대 목록 컴포넌트 제작
  package.json
  pnpm-lock.yaml
  public/icons/invitations.svg
  src/components/Sidebar/index.tsx
  src/containers/mydashboard/DashboardList/index.tsx
  src/containers/mydashboard/InvitedDashboardList/InvitationItemList.tsx
  src/containers/mydashboard/InvitedDashboardList/InvitationSearch.tsx
  src/containers/mydashboard/InvitedDashboardList/index.tsx
  src/containers/mydashboard/index.tsx
  src/services/getService.ts
  src/services/putService.ts
  src/types/Invitation.interface.ts
Labels: ✨ feat, 📑 my dashboard

#97 ✨ Feat: 모달 기능
  public/icons/check.svg
  src/components/Modal/ColumnDeleteModal.tsx
  src/components/Modal/ColumnModifyModal.tsx
  src/components/Modal/DefaultModal.tsx
  src/components/Modal/DeleteDashboardModal.tsx
  src/components/Modal/InviteMemberModal.tsx
  src/components/Modal/NewColumnModal.tsx
  src/components/Modal/NewDashboardModal.tsx
  src/components/Modal/NotificationModal.tsx
  src/components/Modal/index.tsx
  src/components/Sidebar/index.tsx
  src/constants/index.ts
  src/hooks/useModal.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/services/deleteService.ts
  src/services/postService.ts
  src/services/putService.ts
  src/store/reducers/modalSlice.ts
  src/store/store.ts
  src/types/Modal.interface.ts
  src/types/post/ModalPost.interface.ts
Labels: ✨ feat

#105 🎨 Design(#85, #87): 헤더와 사용자 프로필, 드롭다운 디자인 완성
  src/components/Header/DashboardHeader.tsx
  src/components/Header/DashboardHeader/Buttons.tsx
  src/components/Header/DashboardHeader/MemberProfiles.tsx
  src/components/Header/DashboardHeader/index.tsx
  src/components/Header/LandingHeader.tsx
  src/components/Header/UserMenuDropdown.tsx
  src/components/Header/UserProfile.tsx
  src/components/Header/index.tsx
  src/components/ProfileIcon/index.tsx
  src/services/getService.ts
  src/styles/globals.css
  src/utils/findDashboardById.ts
  tailwind.config.ts
Labels: ✨ feat, 🎨 design

#102 ✨ Feat(#27): 비밀번호 변경 기능
  src/components/Input/PwdInput.tsx
  src/containers/mypage/EditProfileForm.tsx
  src/containers/mypage/PwdChangeForm.tsx
  src/hooks/useUpdateProfile.ts
  src/pages/mypage/index.tsx
  src/services/postService.ts
  src/services/putService.ts
  src/types/post/UpdatePasswordForm.interface.ts
  src/types/post/UpdateProfileForm.interface.ts
  src/types/post/UploadImageForm.interface.ts
Labels: ✨ feat, 🪪 mypage

#107 ✨ Feat(#84): 사용자 아이콘 색상 배정 함수 구현과 색상 설정
  src/components/ProfileIcon/index.tsx
  src/constants/index.ts
  src/utils/getProfileColorStyle.ts
Labels: ✨ feat, 🎨 design

#117 ✨ Feat: Card 컴포넌트 (대시보드 페이지)
  public/icons/calendar.svg
  src/containers/dashboard/Card.tsx
  src/containers/dashboard/Column.tsx
  src/containers/dashboard/ColumnsSection.tsx
  src/layouts/MainLayout.tsx
  src/pages/dashboard/[id]/index.tsx
  src/services/getService.ts
  src/services/putService.ts
  src/types/Card.interface.ts
  src/utils/formatDate.ts
  src/utils/formatDateWithDot.tsformatDateWithDot.ts
  src/utils/generateTagColor.ts
  tailwind.config.ts
Labels: ✨ feat, 📄 dashboard

#110 ✨ feat(#104): 사이드바 페이지네이션 구현 및 이동 버튼 추가
  src/components/Sidebar/DashboardItem.tsx
  src/components/Sidebar/index.tsx
  src/containers/mydashboard/InvitedDashboardList/ItemList.tsx
  src/containers/mydashboard/InvitedDashboardList/SearchBar.tsx
  src/containers/mydashboard/InvitedDashboardList/index.tsx
Labels: ✨ feat, 🎨 design

#112 ✨ Feat(#7): 회원가입 모달 연결
  src/components/Modal/EmailExistModal.tsx
  src/components/Modal/SignupSuccessModal.tsx
  src/components/Modal/TextModal.tsx
  src/components/Modal/index.tsx
  src/constants/index.ts
  src/containers/signin&signup/SignUpForm.tsx
  src/pages/signup/index.tsx
  src/types/Modal.interface.ts
Labels: ✨ feat, 🔐 auth

#120 🛠 Fix(#84): 멤버의 프로필색상을 제대로 보여줄 수 있도록 수정
  src/components/Header/DashboardHeader/MemberProfiles.tsx
  src/components/Header/UserProfile.tsx
  src/components/ProfileIcon/index.tsx
  src/containers/dashboard/Card.tsx
Labels: 🛠 fix

#126 🛠 Fix(#118): 새 비밀번호도 글자수 확인하도록 변경
  src/containers/mypage/PwdChangeForm.tsx
Labels: 🛠 fix, 🪪 mypage

#125 🎨 design(#124): 내 대시보드 대시보드 목록 스켈레톤 설정
  package.json
  pnpm-lock.yaml
  src/components/Sidebar/index.tsx
  src/containers/mydashboard/DashboardList/index.tsx
  src/containers/mydashboard/InvitedDashboardList/index.tsx
  src/containers/mydashboard/index.tsx
  src/layouts/MainLayout.tsx
  tailwind.config.ts
Labels: 🎨 design, 📑 my dashboard

#130 ✨ Feat: 태그 목록 컴포넌트
  src/components/Tags/index.tsx
  src/constants/index.ts
  src/containers/dashboard/Card.tsx
  src/containers/dashboard/ColumnsSection.tsx
  src/utils/generateTagColor.ts
  src/utils/generateTagIndex.ts
  tailwind.config.ts
Labels: ✨ feat

#132 ✨ Feat: 로그인 폼, 회원가입 폼 모달 연결 및 모달 리팩토링
  src/components/Modal/ColumnDeleteModal.tsx
  src/components/Modal/ColumnModifyModal.tsx
  src/components/Modal/DefaultModal.tsx
  src/components/Modal/DeleteDashboardModal.tsx
  src/components/Modal/InviteMemberModal.tsx
  src/components/Modal/NewColumnModal.tsx
  src/components/Modal/NewDashboardModal.tsx
  src/components/Modal/NotificationModal.tsx
  src/components/Modal/TextModal.tsx
  src/components/Modal/index.tsx
  src/constants/index.ts
  src/containers/signin&signup/SignInForm.tsx
  src/hooks/useSignIn.ts
  src/pages/index.tsx
Labels: 🔐 auth, 🪧 modal

#128 ✨ Feat: 멤버 컴포넌트
  src/containers/dashboard/edit/MemberItem.tsx
  src/containers/dashboard/edit/MemberList.tsx
  src/containers/dashboard/edit/MembersSection.tsx
  src/pages/dashboard/[id]/edit.tsx
  src/services/deleteService.ts
  src/types/delete/DeleteMemberInput.interface.ts
Labels: ✨ feat, 🎨 design, 📝 dashboard edit

#134 ✨ feat(#40): 대시보드 수정페이지 완성
  src/components/Header/DashboardHeader/index.tsx
  src/components/Header/DefaultHeader.tsx
  src/components/Header/LandingHeader.tsx
  src/containers/dashboard/edit/DashboardEdit.tsx
  src/layouts/MainLayout.tsx
  src/pages/dashboard/[id]/edit.tsx
Labels: ✨ feat, 🎨 design, 📝 dashboard edit
